---
cifar10:
  cifar_vgg16:
    dim1:
      - 0.007
      - 0.07
    dim2:
      - 0.7
      - 1
    dim3:
      - 2
      - 5
    dim4:
      - 0.1
      - 1.0
    dim5:
      - 1.0
      - 5.0
  cifar_resnet18:
    dim1:
      - 0.001
      - 0.007
    dim2:
      - 0.05
      - 0.5
    dim3:
      - 0.1
      - 1.0
    dim4:
      - 1.0
      - 2.0
    dim5:
      - 2
      - 5
cifar100:
  cifar_vgg16:
    dim1:
      - 0.0001
      - 0.001
    dim2:
      - 0.1
      - 2
    dim3:
      - 0.1
      - 1.0
    dim4:
      - 0.1
      - 1.0
    dim5:
      - 0.1
      - 1.0
  cifar_resnet18:
    dim1:
      - 0.00001
      - 0.0009
    dim2:
      - 0.01
      - 0.2
    dim3:
      - 0.01
      - 0.3
    dim4:
      - 0.1
      - 1
    dim5:
      - 0.1
      - 1.0
mnist:
  lenet:
    dim1:
      - 0.1
      - 1
    dim2:
      - 17.36
      - 17.38
    dim3:
      - 80
      - 120
    dim4:
      - 200
      - 400
    dim5:
      - 200
      - 500
  fcnet:
    dim1:
      - 0.002
      - 0.5
    dim2:
      - 1
      - 5
    dim3:
      - 5
      - 25
    dim4:
      - 10
      - 100
    dim5:
      - 35.5
      - 35.6
    dim6:
      - 40
      - 70
    dim7:
      - 40
      - 70
imagenet:
  resnet50:
    dim1:
      - 0.00001
      - 0.0001
    dim2:
      - 0.01
      - 0.1
    dim3:
      - 0.1
      - 1
    dim4:
      - 0.7
      - 1.5
    dim5:
      - 2
      - 3

# ---
# cifar10:
#   cifar_vgg16:
#     dim1:
#       - 0.001
#       - 0.01
#     dim2:
#       - 0.6
#       - 1
#     dim3:
#       - 5
#       - 10
#     dim4:
#       - 10
#       - 15
#     dim5:
#       - 25
#       - 30
#   cifar_resnet18:
#     dim1:
#       - 0.003
#       - 0.01
#     dim2:
#       - 0.1
#       - 0.4
#     dim3:
#       - 1
#       - 2
#     dim4:
#       - 2
#       - 5
#     dim5:
#       - 7
#       - 10
# cifar100:
#   cifar_vgg16:
#     dim1:
#       - 0.001
#       - 0.01
#     dim2:
#       - 0.2
#       - 0.3
#     dim3:
#       - 1.0
#       - 2.0
#     dim4:
#       - 1
#       - 5
#     dim5:
#       - 5
#       - 10
#   cifar_resnet18:
#     dim1:
#       - 0.00001
#       - 0.0009
#     dim2:
#       - 0.01
#       - 0.2
#     dim3:
#       - 0.3
#       - 1.0
#     dim4:
#       - 0.1
#       - 1
#     dim5:
#       - 1
#       - 5
# mnist:
#   lenet:
#     dim1:
#       - 0.1
#       - 1
#     dim2:
#       - 16
#       - 20
#     dim3:
#       - 80
#       - 120
#     dim4:
#       - 200
#       - 400
#     dim5:
#       - 200
#       - 500
# imagenet:
#   resnet50:
#     dim1:
#       - 0.00001
#       - 0.0001
#     dim2:
#       - 0.01
#       - 0.1
#     dim3:
#       - 0.1
#       - 1
#     dim4:
#       - 0.7
#       - 1.5
#     dim5:
#       - 2
#       - 3

